#pragma once
#include <WinSock2.h>
#include <cstdlib>
#include <cstdio>
#include <cassert>
#include <string>
#include <memory>
#include <vector>
#include <iostream>
#include <algorithm>
#include <mutex>
#include <queue>
#include "stream.h"
#include "crypt.h"